- hosts: 127.0.0.1
  tasks:
    - name: Print a hello message
      debug:
        msg: "Hello World!"
    - name: Print out hosts architecture
      debug:
        msg: "Host architecture is {{ ansible_architecture }}"
    - name: Print a message exclusive to x86_64 hosts
      debug:
        msg: "This message is only for x86_64 hosts"
      when: ansible_architecture == "x86_64"
    - name: Print a message exclusive to arm64 hosts
      debug:
        msg: "This message is only for arm64 hosts"
      when: ansible_architecture == "arm64"
    - name: Print a message exclusive to armhf hosts
      debug:
        msg: "This message is only for armhf hosts"
      when: ansible_architecture == "armhf"
