- hosts: 127.0.0.1
  tasks:
    - name: Print a hello message
      debug:
        msg: "Hello World!"
    - name: Print out hosts architecture
      debug:
        msg: "Host architecture is {{ ansible_architecture }}"
