- hosts: 127.0.0.1
  tasks:
    - name: Print a hello message
      debug:
        msg: "Hello World!"
    - name: Print out hosts architecture
      debug:
        msg: "Host architecture is {{ ansible_architecture }}"
    - name: Print a message exclusive to x86_64 hosts
      debug:
        msg: "This message is only for x86_64 hosts"
      when: ansible_architecture == "x86_64"
    - name: Print a message exclusive to arm64 hosts
      debug:
        msg: "This message is only for aaarch64 hosts"
      when: ansible_architecture == "aarch64"
    - name: Print a message exclusive to armv7l hosts
      debug:
        msg: "This message is only for armv7l hosts"
      when: ansible_architecture == "armv7l"
